baseball/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'', include('mlb.urls', namespace = 'mlb')),
]

if settings.DEBUG:
	urlpatterns += [
		url(r'^media/(?P<path>.*)$', serve, {
			'document_root' : settings.MEDIA_ROOT,
		}),

	url(r'^static/(?P<path>.*)$', serve, {
			'document_root' : settings.STATIC_ROOT,
		}),
	]

mlb/urls.py
"""Defines URL patterns for mlb."""

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
app_name = 'mlb'

urlpatterns = [
	# Home page
	url(r'^$', views.index, name='index'),

	# Player page
	url(r'^players/$', views.players, name='players'),

	# Team page
	url(r'^teams/$', views.teams, name='teams'),

	# Individual team page
	url(r'^team/(?P<team_name>[a-z]+)/$', views.team, name='team'),

	# Pictures
	url(r'^pictures/$', views.pictures, name='pictures'),

	# Detail page for a single picture
	url(r'^pictures/(?P<picture_id>\d+)/$', views.picture, name='picture'),
	
	# Picture page
	url(r'^add_picture/$', views.add_picture, name='add_picture'),

	# Projects
	url(r'^projects/$', views.projects, name='projects'),

	# Detail page for a single project
	url(r'^project/(?P<project_name>[A-Za-z]+)/$', views.project, name='project'),

	# Project page
	url(r'^add_project/$', views.add_project, name='add_project'),

	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.conf.urls import url, include
from django.contrib.auth.views import login
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
	# Login page
	url(r'^login/$', login, {'template_name': 'users/login.html'},
			name='login'),

	# Logout page
	url(r'^logout/$', views.logout_view, name='logout'),

	# Registration page
	url(r'^register/$', views.register, name='register'),
]

mlb/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save

class Team(models.Model):
	"""MLB Baseball Team"""
	name = models.CharField(max_length=4)
	full_name = models.CharField(max_length=50)
	#owner = models.ForeignKey(User)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.name

class Player(models.Model):
	"""MLB Baseball Player"""
	name = models.CharField(max_length=100)
	position = models.CharField(max_length=10)
	league = models.CharField(max_length=5)
	games = models.CharField(max_length=10)
	Tav = models.CharField(max_length=7)
	VORP = models.CharField(max_length=7)
	FRAA = models.CharField(max_length=7)
	BWARP = models.CharField(max_length=7)
	team = models.ForeignKey(Team)
	date_modified = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.name

class Picture(models.Model):
    name = models.CharField(max_length=30)
    image = models.FileField(upload_to="static", blank = True, null = True)

    def __str__(self):
        return self.name

class Project(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=300)
	file = models.FileField(upload_to="static", blank = True, null = True)
	calculations = models.FileField(upload_to="static", blank = True, null = True)
	proj_image = models.FileField(upload_to="static", blank = True, null = True)
	
	def __str__(self):
		return self.name

class ProjectPic(models.Model):
	name = models.CharField(max_length=50)
	chart = models.FileField(upload_to="static", blank = True, null = True)
	project = models.ForeignKey(Project)

mlb/forms.py
from django.forms import ModelForm
from mlb.models import Picture, Project
from django import forms

class PictureForm(forms.ModelForm):
	class Meta:
		model = Picture
		fields = ('name', 'image')

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ('name', 'description', 'file', 'calculations', 'proj_image')

mlb/views.py
from django.shortcuts import render, render_to_response, redirect
from bs4 import BeautifulSoup
import urllib.request
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.template import RequestContext, Template
from datetime import datetime, timedelta
import requests

from mlb.models import Team, Player, Picture, Project, ProjectPic
from mlb.forms import PictureForm, ProjectForm





def index(request):
	"""The home page for MLB"""

	wiki = "http://legacy.baseballprospectus.com/standings/index.php?dispgroup=all&submit=Go"
	page = urllib.request.urlopen(wiki)
	soup = BeautifulSoup(page, 'lxml')

	teams, name = [], []
	for row in soup.find_all('option'):
		if row not in teams:
			teams.append(row.get('value'))
			team_name = row.get('value')
			name.append(row.get_text())
			full_name = row.get_text()
			try:
				team = Team.objects.get(name = team_name)
			except Team.DoesNotExist:
				team = None
				if team is None:
					team = Team(name=team_name, full_name=full_name)
					team.save()


	context = {'teams': teams, 'name': name, 'team': team}

	return render(request, 'mlb/index.html', context)


def players(request):

	wiki1 = "http://legacy.baseballprospectus.com/sortable/index.php?cid=1918873"
	page1 = urllib.request.urlopen(wiki1)
	soup1 = BeautifulSoup(page1, 'lxml')

	players = []
	for element in soup1.find_all('tr')[6:1330]:
		players.append(element.a.get_text())
		try:
			player = Player.objects.get(name = element.a.get_text())
			player.league = element.contents[3].get_text()
			player.games = element.contents[6].get_text()
			player.Tav = element.contents[34].get_text()
			player.VORP = element.contents[35].get_text()
			player.FRAA = element.contents[36].get_text()
			player.BWARP = element.contents[37].get_text()
			player.save()
		except Player.DoesNotExist:
			player = None
			if player is None:
				player = Player(name = element.a.get_text(),
				league = element.contents[3].get_text(),
				games = element.contents[6].get_text(),
				Tav = element.contents[34].get_text(),
				VORP = element.contents[35].get_text(),
				FRAA = element.contents[36].get_text(),
				BWARP = element.contents[37].get_text())
				tm = Team.objects.get(name = element.contents[2].get_text().lower())
				player.team = tm
				player.save()

	player_new = Player.objects.all()

	context = {'players': players, 'player_new': player_new}

	return render(request, 'mlb/players.html', context)



@login_required
def team(request, team_name):
	team = Team.objects.get(name = team_name)
	players = team.player_set.all()

	# Make sure the team belongs to the current user.
	#if team.owner != request.user:
	#	raise Http404

	context = {'players': players, 'team': team}

	return render(request, 'mlb/team.html', context)

@login_required
def teams(request):
	teams = Team.objects.all()

	context = {'teams': teams}

	return render(request, 'mlb/teams.html', context)

@login_required
def pictures(request):
	pictures = Picture.objects.all()

	context = {'pictures': pictures}
	
	return render(request, 'mlb/pictures.html', context)

@login_required
def picture(request, picture_id):
	picture = Picture.objects.get(id = picture_id)
	
	# Make sure the team belongs to the current user.
	#if team.owner != request.user:
	#	raise Http404

	context = {'picture': picture}

	return render(request, 'mlb/picture.html', context)

@login_required
def add_picture(request):
	"""Add a new picture."""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = PictureForm()
	else:
		# POST data submitted; process data.
		form = PictureForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('mlb:pictures'))

	context = {'form': form}
	return render(request,'mlb/add_picture.html', context)

@login_required
def projects(request):
	"""Display Projects"""
	projects = Project.objects.all()

	context = {'projects': projects}
	
	return render(request, 'mlb/projects.html', context)

@login_required
def project(request, project_name):
	project = Project.objects.get(name = project_name)
	pro_file = str(project.file)
	pro_calc = str(project.calculations)
	with open(pro_file) as file_object:
		lines = file_object.readlines()
	file_object.close()

	if pro_calc:
		with open(pro_calc) as file_object:
			calcs = file_object.readlines()
		file_object.close()
	else:
		nocalcs = '/Users/mrcrb/Documents/Python/Baseball/ll_env/static/nocalcs.txt'
		with open(nocalcs) as file_object:
			calcs = file_object.readlines()
		file_object.close()

	charts = project.projectpic_set.all()
	

	# Make sure the team belongs to the current user.
	#if team.owner != request.user:
	#	raise Http404

	context = {'project': project, 'lines': lines, 'calcs': calcs, 'charts': charts}

	return render(request, 'mlb/project.html', context)
	
@login_required
def add_project(request):
	"""Add a new project."""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = ProjectForm()
	else:
		# POST data submitted; process data.
		form = ProjectForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('mlb:projects'))

	context = {'form': form}
	return render(request,'mlb/add_project.html', context)


"""def add_picture(request):
	name = Picture.objects.get('name')
	if request.method == 'GET':
		form = PictureForm()
	else:
		name = Picture.objects.get(name = name)
		form = ProductForm(request.POST, request.FILES)
		p = Picture(name = request.POST.get('name'), website = request.POST.get('website'), image = request.FILES['image'])
		print("image", p.picture)
		p.save()

		return redirect('/mlb/teams/')
	return render(request, 'add_picture.html', {'form':form, 'name': name})
	
	
def players(request):
	time_threshold = datetime.now() - timedelta(days=14)
	player_old = Player.objects.filter(date_modified__lt = time_threshold)
	if not player_old:
		wiki1 = "http://legacy.baseballprospectus.com/sortable/index.php?cid=1918873"
		page1 = urllib.request.urlopen(wiki1)
		soup1 = BeautifulSoup(page1, 'lxml')

		players = []
		for element in soup1.find_all('tr')[6:1330]:
			players.append(element.a.get_text())
			try:
				player = Player.objects.get(name = element.a.get_text())
				player.league = element.contents[3].get_text()
				player.games = element.contents[6].get_text()
				player.Tav = element.contents[34].get_text()
				player.VORP = element.contents[35].get_text()
				player.FRAA = element.contents[36].get_text()
				player.BWARP = element.contents[37].get_text()
				player.save()
			except Player.DoesNotExist:
				player = None
				if player is None:
					player = Player(name = element.a.get_text(),
					league = element.contents[3].get_text(),
					games = element.contents[6].get_text(),
					Tav = element.contents[34].get_text(),
					VORP = element.contents[35].get_text(),
					FRAA = element.contents[36].get_text(),
					BWARP = element.contents[37].get_text())
					tm = Team.objects.get(name = element.contents[2].get_text().lower())
					player.team = tm
					player.save()

		player_new = Player.objects.all()

	context = {'players': players, 'player_new': player_new}

	return render(request, 'mlb/players.html', context)"""

mlb/templates/mlb/add_picture.html
{% extends "mlb/base.html" %}

{% load bootstrap3 %}

{% block header %}

<h3><a href="{% url 'mlb:index' %}">MLB HOME PAGE</h3>

{% endblock header %}

<p>PICTURES</p>

{% block content %}


<form action="{% url 'mlb:add_picture' %}" method='post'
      class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add picture</button>
    {% endbuttons %}
</form>

{% endblock content %}

mlb/templates/mlb/add_project.html
{% extends "mlb/base.html" %}

{% load bootstrap3 %}

{% block header %}

<h3><a href="{% url 'mlb:index' %}">MLB HOME PAGE</h3>

{% endblock header %}

{% block content %}


<form action="{% url 'mlb:add_project' %}" method='post' 
      class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add project</button>
    {% endbuttons %}
</form>

{% endblock content %}

mlb/templates/mlb/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MLB</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/baseball.css' %}">

</head>

<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="w3-container w3-grey">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'mlb:index' %}">
                    Chris' Portfolio
                </a>
            </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'mlb:teams' %}">Teams</a></li>
                        <li><a href="{% url 'mlb:players' %}">Players</a></li>
                        <li><a href="{% url 'mlb:pictures' %}">Pictures</a></li>
                        <li><a href="{% url 'mlb:projects' %}">Projects</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                        {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                        {% endif %}
                    </ul>
                    
                </div><!--/.nav-collapse -->            
         </div>
    </nav>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="#" class="w3-bar-item w3-button">Link 1</a>
        <a href="#" class="w3-bar-item w3-button">Link 2</a>
        <a href="#" class="w3-bar-item w3-button">Link 3</a>
    </div>

        <div style="margin-left:15%">
            <div class="w3-container">
                <div class="page-header">

                    {% block header %}{% endblock header %}
                </div>

                <div>
                    {% block content %}{% endblock content %}
                </div>

            </div> <!-- /container -->
        </div>
    
</body>
</html>

mlb/templates/mlb/index.html
{% extends "mlb/base.html" %}

{% block header %}

<div class='jumbotron'>
    <h1>List of all MLB Teams</h1>
</div>

{% endblock header %}

<p>MLB</p>

{% block content %}

<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>
    

{% endblock content %}

mlb/templates/mlb/picture.html
{% extends "mlb/base.html" %}

{% block header %}

<div class="body_boarder">

    <div class="top">
        <h2><a href="{% url 'mlb:index' %}">MLB HOME PAGE</a></h2>
    </div>

    <div class='jumbotron' align="center">
        <h1>{{picture.name}}</h1>
    </div>
</div>

{% endblock header %}

{% block content %}

<div class="add_pic" align="right">

    <h1>
        <a href="{% url 'mlb:add_picture' %}">add new picture</a>
    </h1>
</div>


{% load static %}

{% if picture.image %}
    <div class="thumbnail">
        <img src="{{picture.image.url}}" class="img-responsive" alt="HTML5 Icon" style="width:100%">
    <div class="caption" align="center">
    </div>
        </div>
{% endif %}
{% endblock content %}

mlb/templates/mlb/pictures.html
{% extends "mlb/base.html" %}

{% block header %}

<div class="body_boarder">
    <div class="top">
        <h2><a href="{% url 'mlb:index' %}">MLB HOME PAGE</a></h2>
    </div>

    <div class='jumbotron' align="center">
        <h1>List of all Pictures</h1>
    </div>



</div>

    {% endblock header %}


    {% block content %}
    {% load static %}

    <div class="add_pic" align="right">
        <h3>
            <a href="{% url 'mlb:add_picture' %}">Add picture</a>
        </h3>
    </div>

    {% for picture in pictures %}

    <div class="container-fluid">
        
        <div class="col-md-4">
            <h3>
                <a href="{% url 'mlb:picture' picture.id%}">{{ picture.name }}</a>
            </h3>
            {% if picture.image %}
            <div class="thumbnail">
                <img src="{{picture.image.url}}" style="width:100%">
                <div class="caption" align="center">
                    
                    <h2>{{ picture }}</h2>
                {% endif %}
                </div>
            </div>
        </div>
    </div>


    {% endfor %}


    {% endblock content %}

mlb/templates/mlb/players.html
{% extends "mlb/base.html" %}

{% block header %}

<div class="body_boarder">
    <div class="top">
        <h2><a href="{% url 'mlb:index' %}">MLB HOME PAGE</a></h2>
    </div>

    <div class='jumbotron' align="center">
        <h1>List of all MLB Players</h1>
    </div>

</div>


{% endblock header %}

{% block content %}


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Player Name</th>
            <th scope="col">Team</th>
            <th scope="col">League</th>
            <th scope="col">Games</th>
            <th scope="col">Tav</th>
            <th scope="col">VORP</th>
            <th scope="col">FRAA</th>
            <th scope="col">BWARP</th>
        </tr>
    </thead>
    <tbody>
        {% for player in player_new|slice:":100" %}
        <tr>
            <td>{{player}}</td>
            <th scope="row"><a href="{% url 'mlb:players' %}">{{player.team}}</a></th>
            <td>{{player.league}}</td>
            <td>{{player.games}}</td>
            <td>{{player.Tav}}</td>
            <td>{{player.VORP}}</td>
            <td>{{player.FRAA}}</td>
            <td>{{player.BWARP}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

mlb/templates/mlb/project.html
{% extends "mlb/base.html" %}


    {% block header %}

    <div class="body_boarder">
        <div class="top">
            <h2><a href="{% url 'mlb:projects' %}">MLB TEAM PAGE</a></h2>
        </div>

        <div class='jumbotron' align="center">
            <h1>Code for project: {{project.name}}</h1>
        </div>
    </div>


    {% endblock header %}


    {% block content %}

    {% load static %}
    <table style="width: 100%">
        <tr>
            <th class="project_name"> {{project.name}}</th>
            <th class="add_proj"><a href="{% url 'mlb:add_project' %}">add new project</a></th>
        </tr>
    </table>

<div class="w3-cell-row">
        <div class="w3-container w3-cell w3-margin-top">
                <div class="w3-half w3-margin-top">
                        <p>
                            {% for line in lines %}
                            {{line}}
                            <br />
                            {% endfor %}
                        </p>
                        <br />
                        <h3><b>CALCULATIONS</b></h3>
                        <p>
                            {% for calc in calcs %}
                            {{calc}}
                            <br />
                            {% endfor %}
                        </p>
                </div>
               

            {% load static %}
        <div class="w3-container w3-cell">
            <div class="w3-row-padding w3-margin-top">
                <div class="w3-card w3-margin-top">
                    {% for chart in charts %}
                    <img src="{{chart.chart.url}}" alt="HTML5 Icon" width="100%">
                    {% endfor %}
                </div>
            </div>
            <div class="caption" align="center"></div>
        </div>
    </div>
</div>
 {% endblock content %}

mlb/templates/mlb/projects.html
{% extends "mlb/base.html" %}

{% block header %}

<div class="body_boarder">
    <div class="top">
        <h2><a href="{% url 'mlb:index' %}">MLB HOME PAGE</a></h2>
    </div>

    <div class='jumbotron' align="center">
        <h1>List of all projects</h1>
    </div>

</div>

    {% endblock header %}


    {% block content %}
    {% load static from staticfiles %}
    
    <h1><a href="{% url 'mlb:add_project' %}">Add project</h1>
    <br />



    {% for project in projects %}
    <h3><a href="{% url 'mlb:project' project.name %}">{{ project.name }}</a></h3>
    {{project.description}}
    {% endfor %}

    {% endblock content %}

mlb/templates/mlb/team.html
{% extends "mlb/base.html" %}

{% block header %}


<div class="body_boarder">
    <div class="top" align="left">
        <h2><a href="{% url 'mlb:teams' %}">MLB TEAMS PAGE</a></h2>
    </div>

    <div class='jumbotron' align="center">
        <h1>{{team.full_name}} Players</h1>
    </div>

    <div class="bottom" align="center" border-bottom="5px solid black" border-top="5px solid black">
        <h4>Webscraping, Sorting, Modeling, Inheritance, and Database Queries with Python</h4>
    </div>
</div>



{% endblock header %}

{% block content %}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Player Name</th>
            <th scope="col">League</th>
            <th scope="col">Games</th>
            <th scope="col">Tav</th>
            <th scope="col">VORP</th>
            <th scope="col">FRAA</th>
            <th scope="col">BWARP</th>
        </tr>
    </thead>
    <tbody>
        {% for player in players %}
        <tr>
            <th scope="row"><a href="{% url 'mlb:players' %}">{{player}}</a></th>
            <td>{{player.league}}</td>
            <td>{{player.games}}</td>
            <td>{{player.Tav}}</td>
            <td>{{player.VORP}}</td>
            <td>{{player.FRAA}}</td>
            <td>{{player.BWARP}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

mlb/templates/mlb/teams.html
{% extends "mlb/base.html" %}

{% block header %}


<div class="body_boarder">

        <div class="top">
            <h2><a href="{% url 'mlb:index' %}">MLB HOME PAGE</a></h2>
        </div>

        <div class='jumbotron' align="center">
            <h1>List of all teams</h1>
        </div>
  
</div>

    {% endblock header %}

    {% block content %}

    <div class="body_table">
        <ul>

            {% for team in teams %}

            <h3>
                <a href="{% url 'mlb:team' team.name %}">{{ team.full_name }}</a>
            </h3>

            {% endfor %}

        </ul>
    </div>

    {% endblock content %}